spring:
  datasource:
    url: jdbc:mysql://localhost/terry?useSSL=false&characterEncoding=utf8
    username: terry
    password: database
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect